version: "3.7"

services:
  remix:
    container_name: ${HOST}
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: ${NGINX_HOST}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - remix
